# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b6e31ff0f5a9fee8f3ca6c994ce4980aed23a43790b4ba66340cdbfb969ff854e7bbf193beeec713fc31c0a29265da17de5b0693ccc737b285e69730e27cc3ec

test:
  secret_key_base: 0f5f9ea7ba20f393c32a9bf200177ff5bec7928bbf05bb126e629639d2e9ae7830cb16f5576aa47a189cf1d75a83dd54462dbdd75142c7c0577c57eb66e2a954

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
